### ISSUE TITLE
Error on launching app

### ISSUE THREAD

**Issue by frague59** [encharm/Font-Awesome-SVG-PNG#60]
I've tried to use your app to generate a png set of icons : 

(I've installed the package through npm.)

```
$ ./font-awesome-svg-png.js --color e85500 --sizes 40 --dest e85500/
```

But I have the following error: (I've updated the ./font-awesome-svg-png.js to `trace` the errors)

```
Trace: Caught error [TypeError: Cannot read property 'charCodeAt' of undefined]
    at /home/fguerin/Projects/Font-Awesome-SVG-PNG/font-awesome-svg-png.js:76:11
    at tryCatcher (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/fguerin/Projects/node_modules/font-awesome-svg-png/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I'm on a debian testing:

```
$ node --version 
v4.6.1
```

**Comment by rinobatin** [comment]
Try locking down the dependencies version in package.json.  

```
  "dependencies": {
    "bluebird": "2.9.13",
    "extend": "1.2.1",
    "font-awesome": "4.5.0",
    "graceful-fs": "2.0.1",
    "lodash.indexby": "3.0.0",
    "mkdirp": "0.5.0",
    "optimist": "0.6.0",
    "svgo": "0.4.4",
    "xml2js": "0.4.5"
  }
```

**Comment by rinogo** [comment]
I'm also getting this error.  The change to package.json did not work.

**Comment by rinogo** [comment]
Mac OS X El Capitan (10.11.6), Node version 4.4.3.

**Comment by rinogo** [comment]
Correction, I believe this will work, but in order for the "fix" to work, you can't use the "binary" in your path.  You have to call it directly using Node.

Will not work:
```
font-awesome-svg-png --list
```

Will work:
```
node font-awesome-svg-png.js --list
```

**Comment by rinogo** [comment]
I had this problem again and searched to find my own answer.  Hence the self-directed-thumbs-up. :)

**Comment by rinogo** [comment]
FYI, this "fix" applies to not just the `--list` command, but others also, like:

```
node font-awesome-svg-png.js --color 00adf2 --sizes 512
```

**Comment by Rush** [comment]
Please see latest changes. I apologize for not attending to this repo. Hopefully this latest update amends my absence.
