### ISSUE TITLE
Break generating svg

### ISSUE THREAD

**Issue by Fleury93** [encharm/Font-Awesome-SVG-PNG#69]
Hi, after I enter this command:
font-awesome-svg-png --color red --sizes 128,256 then rise these error: 

```
usr/local/lib/node_modules/font-awesome-svg-png/lib/getIconSvg.js:16
  let paddingTop = (parseInt(verticalPadding / 2)) * PIXEL;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/font-awesome-svg-png/lib/generateSprites.js:6:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/font-awesome-svg-png/lib/generate.js:4:21)
    at Module._compile (module.js:410:26)

```

**Comment by Rush** [comment]
It's due to your Node version being old.
